SELECT generate_person(100);

SELECT generate_card_type();

INSERT INTO account (id_owner, balance) SELECT id_person,RANDOM()*100 as balance FROM person;

INSERT INTO card (id_card_type, id_account, withdrawal_limit) SELECT id_card_type, id_account, RANDOM()*99+1 AS withdrawal_limit from account, cardtype ORDER BY RANDOM() LIMIT 10;


INSERT INTO trader
SELECT nextval('paymentplace_id_payment_place_seq') as id_payment_place, id_account, id_person FROM (SELECT id_account, id_person FROM account, person
ORDER BY RANDOM() LIMIT 30) as rnd;

SELECT generate_atm(10);

--Payment place is generated by trigger

INSERT INTO accepts 
SELECT DISTINCT * FROM (SELECT id_card_type, id_payment_place from paymentplace, cardtype LIMIT 40) nondistinct;

INSERT INTO transaction(id_payment_place,id_account, amount, due_date)
SELECT id_payment_place, id_account, ((RANDOM()*99)+1) AS amount, CURRENT_DATE + RANDOM()* 10 * INTERVAL '1 day' AS due_date FROM account, paymentplace ORDER BY RANDOM() LIMIT 100;
